apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: web-app:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: postgres-config
          livenessProbe:
            timeoutSeconds: 5
            initialDelaySeconds: 5
            periodSeconds: 10
            httpGet:
              path: /api/v1/health
              port: http
          readinessProbe:
            timeoutSeconds: 5
            initialDelaySeconds: 5
            periodSeconds: 10
            httpGet:
              path: /api/v1/ready
              port: http
          startupProbe:
            initialDelaySeconds: 5
            failureThreshold: 4
            httpGet:
              path: /api/v1/ready
              port: http
