apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  # HOST AND PORT ARE FAKE FOR NOW
  POSTGRES_DB: web-app
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: test123
  # postgres service host...can this ever change?
  POSTGRES_HOST: "10.43.185.153"
  POSTGRES_PORT: "5432"

